DEFINE USERNAME = &1
DEFINE FILE_PATH = &2
DEFINE TABLESPACE_NAME = '&&USERNAME._DATA'
DEFINE TABLESPACE_FILE_NAME = '&&FILE_PATH.&&TABLESPACE_NAME..DBF'
DEFINE INDEX_NAME = '&&USERNAME._IDX'
DEFINE INDEX_FILE_NAME = '&&FILE_PATH.&&INDEX_NAME..DBF'

CREATE TABLESPACE "&&TABLESPACE_NAME"
    DATAFILE 
        '&&TABLESPACE_FILE_NAME' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 10G;
CREATE TABLESPACE "&&INDEX_NAME"
    DATAFILE 
        '&&INDEX_FILE_NAME' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 10G;
		
--UNDEFINE USERNAME
UNDEFINE FILE_PATH
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_FILE_NAME
UNDEFINE INDEX_NAME
UNDEFINE INDEX_FILE_NAME