DEFINE USERNAME = &&1

GRANT CREATE SEQUENCE TO &&USERNAME;
GRANT CREATE ANY DIRECTORY TO &&USERNAME;
GRANT CREATE TABLE TO &&USERNAME;
GRANT CREATE TYPE TO &&USERNAME;
GRANT CREATE SYNONYM TO &&USERNAME;
GRANT CREATE SESSION TO &&USERNAME;
GRANT CREATE PROCEDURE TO &&USERNAME;
GRANT CREATE TRIGGER TO &&USERNAME;