DEFINE USERNAME = &&1

DEFINE TABLESPACE_NAME = '&&USERNAME._DATA'
DEFINE INDEX_NAME = '&&USERNAME._IDX'

DROP TABLESPACE "&&TABLESPACE_NAME"
    INCLUDING CONTENTS AND DATAFILES
     CASCADE CONSTRAINTS;
	 
DROP TABLESPACE "&&INDEX_NAME"
    INCLUDING CONTENTS AND DATAFILES
     CASCADE CONSTRAINTS;
	 
UNDEFINE TABLESPACE_NAME
UNDEFINE INDEX_NAME
COMMIT;