DROP VIEW MMF_9_8.F1VIEW;
CREATE VIEW MMF_9_8.F1VIEW AS
SELECT CONCAT( EXTRACT(YEAR FROM e."DATE"),' SEASON') SEASON, TO_CHAR(e."DATE", 'fmmm/dd/yyyy' ) "Date",
CONCAT(cr.NAME,' Grand Prix') EVENT, t.TRACK_NAME CIRCUIT,
CONCAT(CONCAT(d.FIRST_NAME, ' '),d.LAST_NAME) DRIVER,
c.BRAND_NAME "Constructor",
t.LAPS LAPS,
       (CASE WHEN p.FINISH_POSITION = 1 THEN TO_CHAR(trunc(systimestamp)+p."RESULT",'HH24:MI:SS') 
       ELSE   
       (
       SELECT to_char(extract(SECOND FROM p."RESULT" - p3."RESULT"), 'fm00.000')
       FROM PARTICIPANT p3
       WHERE p3.EVENT_ID = p.EVENT_ID AND p3.FINISH_POSITION = 1
       )
       END) "Time",
p.POINTS POINTS,
p.START_POSITION START_DRIVER_PLACE,
--POLE_POSITION
(SELECT CONCAT(CONCAT(d2.FIRST_NAME, ' '),d2.LAST_NAME) FROM PARTICIPANT p2
INNER JOIN DRIVER d2 ON d2.ID = p2.DRIVER_ID 
WHERE p2.START_POSITION = 1 AND p2.EVENT_ID = e.ID) POLE_POSITION,
--WINNER
(SELECT CONCAT(CONCAT(d2.FIRST_NAME, ' '),d2.LAST_NAME) FROM PARTICIPANT p2
INNER JOIN DRIVER d2 ON d2.ID = p2.DRIVER_ID 
WHERE p2.FINISH_POSITION = 1 AND p2.EVENT_ID = e.ID) WINNER,
--DRIVER_WINS
(SELECT COUNT(*) FROM PARTICIPANT p2
WHERE p2.FINISH_POSITION = 1 AND p2.DRIVER_ID = d.ID) DRIVER_WINS,
--CONSTRUCTOR_WINS
(SELECT COUNT(*) FROM PARTICIPANT p2
WHERE p2.FINISH_POSITION = 1 AND p2.CONSTRUCTOR_ID = c.ID) CONSTRUCTOR_WINS
FROM PARTICIPANT p
INNER JOIN DRIVER d ON d.ID = p.DRIVER_ID 
INNER JOIN "CONSTRUCTOR" c ON c.ID = p.CONSTRUCTOR_ID
INNER JOIN EVENT e ON e.ID = p.EVENT_ID 
INNER JOIN TRACK t ON t.ID = e.TRACK_ID 
INNER JOIN COUNTRY cr ON cr.ID = t.COUNTRY_ID
ORDER BY SEASON DESC, e."DATE" ASC, p."RESULT" ASC;
COMMIT;